# Generated by Django 4.0.3 on 2022-04-14 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projects_end_date_alter_projects_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='dev',
            field=models.TextField(choices=[('1', 'Thanh Dang'), ('2', 'Thao Dao'), ('3', 'Thanh Lim'), ('4', 'Nha Thanh'), ('5', 'Phan Oanh')], default='0', max_length=50),
        ),
    ]
